In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([2,3,4])
print(arr2)

[1 2 3]
[2 3 4]


In [3]:
arr1 + arr2

array([3, 5, 7])

In [4]:
arr1+4

array([5, 6, 7])

In [5]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[2],[4],[5]])
print(arr2)

[1 2 3]
[[2]
 [4]
 [5]]


In [6]:
arr1 + arr2

array([[3, 4, 5],
       [5, 6, 7],
       [6, 7, 8]])

In [7]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6,7])

In [8]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 