In [2]:
import numpy as np
numpy_array = np.array([1,2,3])
numpy_array

array([1, 2, 3])

In [3]:
#2 dimensional
import numpy as np
numpy_array = np.array([[1,2,3],[2,4,8],[1,3,5]])
numpy_array

array([[1, 2, 3],
       [2, 4, 8],
       [1, 3, 5]])

In [4]:
numpy_array.dtype

dtype('int64')

In [22]:
numpy_array.itemsize

8

In [5]:
numpy_array.shape

(3, 3)

In [6]:
numpy_array.size

9

In [7]:
numpy_array.ndim

2

In [11]:
zeros = np.zeros((2,3))
zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
zeros.dtype

dtype('float64')

In [14]:
zeros = np.zeros((2,3),dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
zeros.dtype

dtype('int64')

In [16]:
ones=np.ones((3,3),dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
arr_r = np.arange(10)
arr_r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr_d = np.linspace(1,5,10)
arr_d

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])