In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
# I want to change the shape of array 1D -2D

In [6]:
reshaped = arr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
#To revert from Reshaped arr

In [8]:
flattened = reshaped.flatten()
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
raveled = reshaped.ravel()
raveled

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
flattened = reshaped.flatten()
flattened[0]=99
flattened


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
raveled = reshaped.ravel()
raveled[1]=88
raveled

array([ 1, 88,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
reshaped

array([[ 1, 88,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#when we change the value in flattened it doesn't effect the original one. when you print reshaped it gives original array
#but it's not the same with raveled. It changes the original array