In [1]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[1:]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr[1:2]

array([[4, 5, 6]])

In [6]:
arr[0:1]

array([[1, 2, 3]])

In [7]:
arr[0:1,2:3]

array([[3]])