In [1]:
import numpy as np


In [3]:
arr =np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr[0][1]

np.int64(2)

In [5]:
arr[0][2]

np.int64(3)

In [6]:
arr[1][2]

np.int64(6)

In [7]:
arr[1,2]

np.int64(6)

In [8]:
arr_new =np.array([7,8,9])

In [9]:
arr_new

array([7, 8, 9])

In [10]:
arr_new[-1]

np.int64(9)

In [11]:
arr[-1]

array([4, 5, 6])

In [12]:
arr[1][1]=55

In [13]:
arr

array([[ 1,  2,  3],
       [ 4, 55,  6]])

In [14]:
arr[1]=7
arr

array([[1, 2, 3],
       [7, 7, 7]])

In [15]:
arr[0] + 2

array([3, 4, 5])

In [16]:
arr

array([[1, 2, 3],
       [7, 7, 7]])